config/routes.rb
Blog::Application.routes.draw do

  root :to => 'posts#index'
  resources :tags, only: [:show]
  resources :posts, only: [:index, :show]
  match "/about", to: "pages#about"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :string(255)
#

class Post < ActiveRecord::Base
  include MarkdownHelper
  attr_accessible :content, :title, :tag_ids, :description
  has_and_belongs_to_many :tags

  validates :title, presence: true, length: { maximum: 255 }
  validates :description, length: { maximum: 255 }
  validates :content, presence: true

  def to_param
    "#{id}-#{title.parameterize}"
  end

  # Public: Get the 30 first words of the post's content, taking care of
  # html tags.
  #
  # Returns a String, the truncated post content.
  def truncated_content link = ""
    HTML_Truncator.truncate(
      markdown(content),
      30,
      ellipsis: link.blank? ? "..." : "... #{link}"
    ).html_safe
  end

end

app/models/posts_tags.rb
# == Schema Information
#
# Table name: posts_tags
#
#  id      :integer          not null, primary key
#  post_id :integer
#  tag_id  :integer
#

class PostsTags < ActiveRecord::Base
  attr_accessible :post_id, :tag_id
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id    :integer          not null, primary key
#  label :string(255)
#

class Tag < ActiveRecord::Base
  attr_accessible :label
  has_and_belongs_to_many :posts

  validates :label, presence: true, length: { maximum: 40 }

  def to_s ; label ; end

  def to_param
    "#{id}-#{label.parameterize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all(order: 'created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @posts = @tag.posts.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_gravatar(options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest('xavier.nayrac@gmail.com')
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: 'Xavier Nayrac', class: "gravatar")
  end

  def full_title(page_title)
    base_title = "lkdjiin's blog"
    if page_title.empty?
      "#{base_title} - Confessions d'un développeur"
    else
      "#{base_title} - #{page_title}"
    end
  end
end

app/helpers/markdown_helper.rb
# -*- encoding: utf-8 -*-

module MarkdownHelper

  # Render markdown to html
  #
  # content - String in markdown to render in html.
  #
  # Returns a html String.
  def markdown(content)
    @@markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    @@markdown.render(content).html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  # Public: Get the tags of this post ready to be display in html.
  #
  # Returns a html formatted String.
  def labeled_tags tags
    tags.map do |t|
      link_to content_tag(:span, t, class: "label"), tag_path(t)
    end.join(' ').html_safe
  end
end

app/views/layouts/_header.html.haml
.container-fluid.header

app/views/layouts/_sidebar.html.haml
.sidebar
  %h1.gamma= link_to "lkdjiin's blog", root_path
  %h2.delta= link_to "Confessions d'un développeur", root_path
  = link_to image_tag('pen75.png'), root_path
  %div.sidebar-about
    Articles sur mon travail d'entrepreneur et de développeur du Web et
    d'ailleurs.
  %div.sidebar-link= link_to 'qui suis-je ?', about_path
  %div.sidebar-link
    = link_to '@lkdjiin', 'https://twitter.com/lkdjiin', target: "_blank"
  %div.sidebar-link= link_to 'rss', posts_path(format: :rss)

app/views/layouts/application.html.haml
!!! 5
%html{ lang: "fr" }
  %head
    = render "layouts/fonts"
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ charset: "UTF-8" }
    %meta{ content: "#{yield(:description)}", name: "description"}/
    %meta{ content: "#{yield(:keywords)}", name: "keywords"}/
    = auto_discovery_link_tag(:rss, "localhost:3000")
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all"
    = csrf_meta_tags

  %body
    .container-fluid
      .container-narrow
        .row-fluid
          .span3
            = render "layouts/sidebar"
          .span9.content
            = yield
    = debug(params) if Rails.env.development?
    = javascript_include_tag "application"

app/views/pages/about.html.haml
- provide(:description, 'À propos de lkdjiin (xavier nayrac), entrepreneur et développeur')
- provide(:keywords, 'blog, lkdjiin, freelance, xavier nayrac, travail, expérience')
- provide(:title, 'À propos')
%h1 À propos
= my_gravatar(size: 128)
%p
  Dès que j'aurais trouver un truc intéressant à dire, je remplirais cette page.

app/views/posts/index.html.haml
- provide(:description, 'Blog de lkdjiin (xavier nayrac), développeur et entrepreneur')
- provide(:keywords, 'blog, article, lkdjiin, xavier nayrac, entrepreneur, ruby, rails')
- @posts.each do |p|
  .teaser
    %h1.beta= link_to p.title, post_path(p)
    .post-date= l p.created_at, format: "%e %B %Y"
    .post-tags= labeled_tags(p.tags)
    = p.truncated_content link_to("Lire cet article", post_path(p))

= render "shared/top_page"

app/views/posts/show.html.haml
- provide(:description, @post.description)
- provide(:keywords, @post.tags.join(','))
- provide(:title, @post.title)
.post
  %h1= @post.title
  .post-date= l @post.created_at, format: "%e %B %Y"
  = markdown(@post.content)
  .post-tags= labeled_tags(@post.tags)

= render "shared/top_page"

app/views/shared/_top_page.html.haml
.top-page
  = link_to "Top of the page", "#"
  = link_to image_tag('arrow_up75.png'), "#"

app/views/tags/show.html.haml
- provide(:description, "Mes articles à propos de #{@tag.label}")
- provide(:keywords, "blog, article, lkdjiin, liste, sujet, xavier nayrac, #{@tag.label}")
- provide(:title, "Articles pour #{@tag.label}")
%h1.tag-page= "Articles pour <span class='label'>#{@tag.label}</span>".html_safe

- @posts.each do |p|
  %article.tag
    %h2.gamma= link_to p.title, post_path(p.id)
    .post-date= l p.created_at, format: "%e %B %Y"
    .post-tags= labeled_tags(p.tags)